# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('updated', models.DateField(auto_now=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('code', models.CharField(max_length=2)),
                ('flag', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('year', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('IP', 'Intellectual Property Sales'), ('GNI', 'Gross National Income'), ('GDP', 'Gross Domestic Product'), ('FDI', 'Foreign Direct Investment')], max_length=30)),
                ('value', models.FloatField(blank=True)),
                ('description', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.Country')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='slides',
            field=models.ManyToManyField(blank=True, to='analytics.EconomicSnapshot'),
        ),
    ]
