# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
