# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicsnapshot',
            name='type',
            field=models.CharField(choices=[('IP', 'Intellectual Property Sales'), ('PAT', 'Patent Applications'), ('GNI', 'Gross National Income'), ('GDP', 'Gross Domestic Product'), ('FDI', 'Foreign Direct Investment')], max_length=100),
        ),
    ]
