# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20170622_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicsnapshot',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
